### ISSUE TITLE
Use a suru icon

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ciborium#2]
The current icon stands out as being very different from the rest of the icons and not in the suru style at all.

**Comment by Flohack74** [comment]
Its using an external one from Humanity: https://github.com/ubports/ciborium/search?utf8=%E2%9C%93&q=media-memory-sd&type=

**Comment by dpniel** [comment]
Do we have a suru icon for this or is there someone we can ask to create one?

**Comment by Flohack74** [comment]
Its on the way to Sam Hewitt :)

**Comment by UniversalSuperBox** [comment]
Fixed by #14
