### ISSUE TITLE
Don't mount everything by default

### ISSUE THREAD

**Issue by ghost** [ubports/ciborium#38]
By default, Ciborium tries to mount every partition on mass storage devices and throws a warning pop-up when it fails.

On the PinePhone, it even tried to mount partitions on the internal eMMC storage, but this was [fixed](https://gitlab.com/ubports/community-ports/pinephone/-/merge_requests/6) recently, enabling Ciborium on the PinePhone as well.

However, the usage pattern of the PinePhone differs from Halium-based ports. People are not just inserting an SD card with a FAT32 partition to put their music and photo's on, but they also tend to insert SD cards with multibootloaders, other OS'es, JumpDrive, and so on.

When Ciborium starts, it tries to mount all such partitions, and fails to do so. Then it spams the user with notifications of its failure, which is annoying.

There are numerous ways to solve this problem. Just from the top of my head:

- Implement some sort of checkbox mechanism, where the user can select which partitions Ciborium should automount at boot;
- Do a filesystem check prior to mounting, to determine whether it's actually mass storage or something else;
- Disable the notifications (set `/com/ubuntu/NotificationSettings/dpkg/ciborium/enable-notifications` to `false` by default), although that's not really a 'fix'.

**Comment by dobey** [comment]
Moved to GitLab at https://gitlab.com/ubports/core/ciborium/-/issues/1
